### ISSUE TITLE
Deliver theme inheritance : loose dropdown functionnality

### ISSUE THREAD

**Issue by itanea** [getgrav/grav-theme-deliver#10]
It's not really an issue.
It's more like support ;-)

When I apply recommandations in [this official post](https://getgrav.org/blog/theme-development-with-inheritance), I loose the dropdown menu capacity.

I try to add in my /user/themes/mydeliver/mydeliver.yaml the dropdown section (on the top and on the bottom) without success :
```
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '':
          - user/themes/mydeliver
          - user/themes/deliver

dropdown:
  enabled: true
```

But when in the system.yaml, I change this :

```
pages:
  theme: mydeliver
```

to this :

```
pages:
  theme: deliver
```

the dropdown functionnality works.

Please can you help me ?
