### ISSUE TITLE
Question: Autoslide

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav-theme-deliver#2]
What are the autoslide options and where should they be added? I noticed them in showcase.html.twig.

**Comment by hexplor** [comment]
See user/site.yaml:
```yaml
header_options:
  arrows: 'true'                            # Create Next and previous button
  autoslide: 'false'                        # Auto slideshow mode
  autoslideHoverStop: 'false'               # Pause auto slideshow mode on mouseover
  interval: '2000'                          # The interval between each slide (Interval in millisecond)
  loop: 'false'                             # Infinite slideshow             
  transition : zoom                         # Set the animation kind (fade/slide/page/zoom)
  itemsForSlide: '0'                        # Wrap each 'n' item
  touch: 'true'                             # Set a native slide for touch device
  swipe : 'true'                            # Enable swipe for touch device
```
