### ISSUE TITLE
Showcase slider broken after release 2.0

### ISSUE THREAD

**Issue by lownoise2** [getgrav/grav-theme-deliver#44]
the images are placed below each other instead of it being a slider from left to right

![Image](https://github.com/user-attachments/assets/a83f4398-6344-4842-939d-4b7489e9be0f)

**Comment by herr-schreiber** [comment]
Hey, got the same problem, found a workaround:

in templates\modular\showcase.html.twig the variables for the different fields are 
`<script type="text/javascript">

$('#content-slide').slideme({
  arrows: {{ page.header.slide_settings.arrows}},
  autoslide: {{ page.header.slide_settings.autoslide }},
  autoslideHoverStop: {{ page.header.slide_settings.autoslideHoverStop}},
  interval: {{ page.header.slide_settings.interval}},
  loop: {{ page.header.slide_settings.loop }},
  pagination: "numbers",
  transition : '{{ page.header.slide_settings.transition }}',
  itemsForSlide: {{ page.header.slide_settings.itemsForSlide }},
  touch: {{ page.header.slide_settings.touch}},
  swipe: {{ page.header.slide_settings.swipe}}

});
</script>`

but the values are set in the "site.yaml".  I think "page.header" would be set in the frontmatter or so, but I changed it to
`<script type="text/javascript">

$('#content-slide').slideme({
  arrows: {{ site.header_options.arrows}},
  autoslide: {{ site.header_options.autoslide }},
  autoslideHoverStop: {{ site.header_options.autoslideHoverStop}},
  interval: {{ site.header_options.interval}},
  loop: {{ site.header_options.loop }},
  pagination: "numbers",
  transition : '{{ site.header_options.transition }}',
  itemsForSlide: {{ site.header_options.itemsForSlide }},
  touch: {{ site.header_options.touch}},
  swipe: {{ site.header_options.swipe}}

});`

and now it works again.

**Comment by herr-schreiber** [comment]
tl;dr : 

@ templates\modular\showcase.html.twig
-> replace _page.header.slide_settings_ with _site.header_options_

---
Hey, got the same problem, found a workaround:

in templates\modular\showcase.html.twig the variables for the different fields are

```
<script type="text/javascript">

$('#content-slide').slideme({
arrows: {{ page.header.slide_settings.arrows}},
autoslide: {{ page.header.slide_settings.autoslide }},
autoslideHoverStop: {{ page.header.slide_settings.autoslideHoverStop}},
interval: {{ page.header.slide_settings.interval}},
loop: {{ page.header.slide_settings.loop }},
pagination: "numbers",
transition : '{{ page.header.slide_settings.transition }}',
itemsForSlide: {{ page.header.slide_settings.itemsForSlide }},
touch: {{ page.header.slide_settings.touch}},
swipe: {{ page.header.slide_settings.swipe}}

});
</script> 
```


but the values are set in the "site.yaml". I think "page.header" would be set in the frontmatter or so, but I changed it to
```
<script type="text/javascript">

$('#content-slide').slideme({
arrows: {{ site.header_options.arrows}},
autoslide: {{ site.header_options.autoslide }},
autoslideHoverStop: {{ site.header_options.autoslideHoverStop}},
interval: {{ site.header_options.interval}},
loop: {{ site.header_options.loop }},
pagination: "numbers",
transition : '{{ site.header_options.transition }}',
itemsForSlide: {{ site.header_options.itemsForSlide }},
touch: {{ site.header_options.touch}},
swipe: {{ site.header_options.swipe}}

});
```

and now it works again.

**Comment by eightysixed** [comment]
Came here to post the same thing 👍  Thanks for the fix. Hopefully this will get patched in :)

**Comment by pmoreno-rodriguez** [comment]
Since version 2, the logic to save the slider values of the showcase template has been changed. Now it is saved in each page that contains a showcase template, in this way you can have different options in each of them, something that does not happen if you save the values of the slider in site.yaml, which would make all pages with showcase have the same configuration.

**Comment by herr-schreiber** [comment]
Did not try to create different templates. I understand the advanteges of creating different settings for different sites, but I was not able to get it working.

If I add the slider settings manually in the frontmatter, they at least appear in the source code of the page - but it remains broken

**Comment by pmoreno-rodriguez** [comment]
Hello. On a clean Grav install, I just downloaded the Deliver theme and added a Modular Home page. I added a Showcase module, added three images, and configured the slider options that appear in the page's admin panel (new since version 2). The body_classes of the Home page (being modular) should be: `modular header-image fullwidth` (indicated in the field description in the admin panel). Everything works perfectly! Here are some screenshots.

![Image](https://github.com/user-attachments/assets/2f43ee94-e4ba-4ac6-addf-2f7f06321e6e)

**Configuration for _showcase.md:**
```
title: Showcase
body_classes: modular
slide_settings:
    arrows: 'true'
    autoslide: 'true'
    autoslideHoverStop: 'true'
    loop: 'true'
    touch: 'true'
    swipe: 'true'
    transition: zoom
    interval: 2000
    itemsForSlide: 1
media_order: 'pic01.jpg,pic02.jpg,pic03.jpg'
slides:
    -
        image: pic01.jpg
        blend: overlay
        backcolor: '#b81f1f'
        heading: 'We <strong>deliver</strong> nothing short of awesome !'
        subheading: 'Check out our portfolio to see our great work..'
        button_text: PORTFOLIO
        button_url: 'http://learn.getgrav.org'
    -
        image: pic02.jpg
        blend: overlay
        backcolor: '#4b3491'
        heading: 'Aenean lacinia <strong>bibendum</strong> nulla sed consectetur. !'
        subheading: 'Etiam porta sem malesuada magna mollis euismod..'
        button_text: LOREM
        button_url: 'http://learn.getgrav.org'
    -
        image: pic03.jpg
        blend: overlay
        backcolor: '#778010'
        heading: 'Cras  <strong>justo</strong> odio, dapibus ac facilisis in, quam.. !'
        subheading: 'Donec ullamcorper nulla non metus auctor fringilla..'
        button_text: DONEC
        button_url: 'http://learn.getgrav.org'
```

**Configuration for home.md:**

```
title: Home
body_classes: 'modular header-image fullwidth'
show_title: '1'
title_bg_choice: color
show_featured_image: false
big_header: false
onpage_menu: '0'
content:
    items: '@self.modular'
```
